device-xiaomi-elish: fix openrc install bug
Add missing depends to the openrc subpackage to ensure they get
installed before trying to enable those services. Otherwise it may fail:

(350/925) Installing device-xiaomi-elish-openrc (4-r0)
Executing device-xiaomi-elish-openrc-4-r0.post-install
 * service qbootctl added to runlevel default
 * rc-update: service `hexagonrpcd-sdsp' does not exist
ERROR: device-xiaomi-elish-openrc-4-r0.post-install: script exited with error 1
(351/925) Installing hexagonrpcd-openrc (0.3.2-r1)

Related: https://builds.sr.ht/~postmarketos/job/1472494#task-img_boe-757

Part-of: https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/6425