temp/update-sysfs: fork from Alpine edge
Fix for:
ERROR: unable to select packages:
  update-sysfs (no such package):
    required by: postmarketos-tweaks-setting-definitions-pinephone-1.1.0-r0[update-sysfs]

Signed-off-by: Oliver Smith <ollieparanoid@postmarketos.org>