systemd/phosh: rebuild against libgnome-desktop-3.so.21
Should partially fix this:

ERROR: unable to select packages:
  so:libgnome-desktop-3.so.20 (no such package):
    required by: phoc-0.57.0-r1[so:libgnome-desktop-3.so.20]
                 phosh-99990.57.0-r2[so:libgnome-desktop-3.so.20]
                 libphosh-99990.57.0-r2[so:libgnome-desktop-3.so.20]
  so:libedataserver-1.2.so.27 (no such package):
    required by: phosh-99990.57.0-r2[so:libedataserver-1.2.so.27]
  .pmbootstrap-20261001.183758:
    masked in: cache
    satisfies: world[.pmbootstrap=20261001.183758]

Signed-off-by: Stefan Hansson <newbyte@postmarketos.org>
Part-of: <https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/9670>