device-google-manta: fix depends on wrong firmware
The v26.06 branch still has a nonfree_firmware function (in main this
was removed in 10e2244d75471bf857a1b425a513bc888842e018, which was not
backported). In this function, the old firmware pkgname is still
referenced, causing errors when building the image:

ERROR: unable to select packages:
  firmware-samsung-manta (no such package):
    required by: device-google-manta-nonfree-firmware-16-r0[firmware-samsung-manta]

Related: https://builds.sr.ht/~postmarketos/job/1786529
Signed-off-by: Oliver Smith <ollieparanoid@postmarketos.org>