linux-purism-librem5: adjust INSTALL_MOD_PATH
Fix for:
ERROR: Please set INSTALL_MOD_PATH to '"$pkgdir"/usr'.

Signed-off-by: Oliver Smith <ollieparanoid@postmarketos.org>
Part-of: <https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/8693>
(cherry picked from commit 092da83b9e81a79a7ef351b85e6b6a6b86e14da8)