device-tokio-techbook: add missing u-boot-tools makedependendency
During build, only makedepends are installed so this is missing.

    /usr/bin/abuild: line 21: mkimage: not found
    >>> ERROR: device-tokio-techbook: build failed