temp/iio-sensor-proxy: rebuild to use libssc.so.2
ERROR: unable to select packages:
  so:libssc.so.1 (no such package):
    required by: iio-sensor-proxy-99993.8-r5[so:libssc.so.1]

Signed-off-by: Aster Boese <asterboese@mailbox.org>
Part-of: <https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/8006>