u-boot-rock64: add py3-setuptools to makedepends
Fix for:
  ModuleNotFoundError: No module named 'distutils'

Signed-off-by: Oliver Smith <ollieparanoid@postmarketos.org>
Part-of: <https://gitlab.postmarketos.org/postmarketOS/pmaports/-/merge_requests/8685>
(cherry picked from commit e7e8fcb2e31c013d3afdfc4d0b744845ea4bae42)